# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(192834)
$foreground = rgb(7B9EB7)
$color0 = rgb(192834)
$color1 = rgb(277FBE)
$color2 = rgb(80BF40)
$color3 = rgb(A6F655)
$color4 = rgb(4299D7)
$color5 = rgb(80BF40)
$color6 = rgb(47ADF5)
$color7 = rgb(7B9EB7)
$color8 = rgb(3D5E76)
$color9 = rgb(8CDD3C)
$color10 = rgb(223644)
$color11 = rgb(335166)
$color12 = rgb(466B86)
$color13 = rgb(AFDDFE)
$color14 = rgb(73B234)
$color15 = rgb(D1ECFF)
